### PR TITLE
Add Python 3.6 to the testing

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Review by icemac — CHANGES_REQUESTED** [review]
Thank you for your PR.
Please add version 3.6 to `setup.py` and write a Change log entry, too.

**Comment by cclauss** [comment]
Python 3.6 tests seem good but...  It looks like Python 3.3 is failing because `ZEO 5.0.4` only supports Python 3.4 or better (Details at https://travis-ci.org/zopefoundation/zope.mkzeoinstance/jobs/205026689).  **Do you really need to support Python 3.3?**

**Review by icemac — APPROVED** [review]

**Comment by icemac** [comment]
@cclauss Python 3.3 has its sunset in September of this year, so let's drop it to get Travis green.

**Comment by cclauss** [comment]
Ready.

**Comment by icemac** [comment]
@cclauss Thank you for your contribution and the patience you had with us. I requested a release in #5.

**Pull request merged**
