### PR TITLE
Optional `blob_dir` parameter

### LINKED ISSUE #17: Make parameter `blob_dir` optional when using `create()` api.
The newly implemented parameter `blob_dir` causes a traceback when its missing in `params` for `ZEOInstanceBuilder().create(location, params)`. See https://github.com/plone/plone.recipe.zeoserver/pull/45#issuecomment-1531537732

### PR DESCRIPTION
**Pull request by petschki**
fixes #17

### CODE REVIEW

**Review by icemac — COMMENTED** [review]
I am convinced that this works, but the solution is a bit surprising as reading a parameter now might lead to a write operation.

Could you add a test verifying that the issue no longer occurs?

**Comment by petschki** [comment]
@icemac done

**Review by icemac — APPROVED** [review]
Thank you for fixing this issue.

**Comment by icemac** [comment]
Just released https://pypi.org/project/zope.mkzeoinstance/5.1.1/ with this fix.

**Pull request merged**
